---
- name: Configurar /etc/kubernetes/config
  lineinfile:
    path: /etc/kubernetes/config
    regexp: '^KUBE_MASTER'
    line: 'KUBE_MASTER="--master=http://192.168.122.10:8080"'
  tags: kubeconfig

- name: Configurar /etc/kubernetes/apiserver
  lineinfile:
    path: /etc/kubernetes/apiserver
    regexp: '^KUBE_API_ADDRESS='
    line: 'KUBE_API_ADDRESS="--insecure-bind-address=0.0.0.0"'
  tags: kubeapi

- name: Configurar /etc/kubernetes/apiserver
  lineinfile:
    path: /etc/kubernetes/apiserver
    regexp: '^KUBE_ETCD_SERVERS='
    line: 'KUBE_ETCD_SERVERS="--etcd-servers=http://192.168.122.10:2379"'
  tags: kubeapi

- name: Configurar /etc/etcd/etcd.conf
  lineinfile:
    path: /etc/etcd/etcd.conf
    regexp: '^ETCD_LISTEN_CLIENT_URLS='
    line: 'ETCD_LISTEN_CLIENT_URLS="http://0.0.0.0:2379"'
  tags: etcd

- name: Configurar /etc/etcd/etcd.conf
  lineinfile:
    path: /etc/etcd/etcd.conf
    regexp: '^ETCD_ADVERTISE_CLIENT_URLS='
    line: 'ETCD_ADVERTISE_CLIENT_URLS="http://0.0.0.0:2379"'
  tags: etcd
 
- name: Configurar /etc/kubernetes/controller_manager
  lineinfile:
    path: /etc/kubernetes/controller-manager
    regexp: '^KUBE_CONTROLLER_MANAGER_ARGS=""'
    state: absent
  tags: controller

- name: Configurar /etc/kubernetes/controller_manager
  shell: 
    cmd: echo 'service account "default"' >> /etc/kubernetes/controller-manager && echo 'KUBE_CONTROLLER_MANAGER_ARGS="--service-account-private-key-file=/var/run/kubernetes/apiserver.key --root-ca-file=/var/run/kubernetes/apiserver.crt"' >> /etc/kubernetes/controller-manager
  tags: controller
...
