---
- name: Stop firewalld
  systemd:
    name: firewalld
    state: stopped
    masked: yes

- name: Deshabilitar selinux
  shell:
    cmd: sed -i s/SELINUX=enforcing/SELINUX=disabled/g /etc/selinux/config && setenforce 0
...
